### ISSUE TITLE
All work

### ISSUE THREAD

**Issue by valeryepwi** [kip-hart/MicroStructPy#1]

**Comment by kip-hart** [comment]
I have not added MicroStructPy to PyPI yet. I am still working on syncing the documentation with readthedocs. `pip install microstructpy` should work in a couple of days, sorry for the delay.

**Comment by kip-hart** [comment]
MicroStructPy has been uploaded to PyPI (https://pypi.org/project/MicroStructPy/) and installs using `pip install microstructpy`. Please let me know if it still does not work.
