### ISSUE TITLE
abaqus export: element node datatype

### ISSUE THREAD

**Issue by MayaStr** [kip-hart/MicroStructPy#58]
**Describe the bug**
I have exported a triangular mesh with the abaqus format. When trying to import the file using meshio, I got
`ValueError: invalid literal for int() with base 10: ' 3294.0'`
The error seems to be caused by the element section in the  .inp file, which starts by 
`*Element, type=C3D4
1, 3294.0, 2393.0, 2976.0, 4753.0
2, 56.0, 57.0, 2333.0, 2077.0
3, 2072.0, 2393.0, 3294.0, 4753.0`
I suppose the values should be ints? Of course, this could also be a bug in the meshio read function. 

**To Reproduce**
```
import microstructpy as msp
import scipy.stats

# Create Materials 
m1 = {
    'name': 'm1',
    'volume': scipy.stats.lognorm(scale=0.5, s=0.95),
    'size': 1,
    'shape': 'sphere',
    'fraction': 9
}
m2 = {
    'name': 'm2',
    'volume': scipy.stats.lognorm(scale=1, s=0.95),
    'size': 0.2,
    'shape': 'sphere',
    'fraction': 1
}
materials = [m1,m2]
# Create Domain
domain = msp.geometry.Cube(side_length=7, corner=(0, 0, 0))

# Create List of Un-Positioned Seeds
seed_area = domain.volume
rng_seeds = {'size': 1}
seeds = msp.seeding.SeedList.from_info(materials,
                                       seed_area,
                                       rng_seeds)

# Position Seeds in Domain
seeds.position(domain)
# Create Polygonal Mesh
pmesh = msp.meshing.PolyMesh.from_seeds(seeds, domain)
# Create Triangular Mesh
tmesh = msp.meshing.TriMesh.from_polymesh(pmesh,materials, mesher='gmsh')
tmesh.write( 'trimesh.inp',format = "abaqus",polymesh=pmesh)

import meshio
mesh = meshio.read("trimesh.inp")
```

**Expected behavior**
Meshio imports .inp

**Desktop (please complete the following information):**
Linux 4.11.0-1-amd64 #1 SMP Debian 4.11.6-1 (2017-06-19) x86_64 GNU/Linux
in Jupyter notebook

**Comment by kip-hart** [comment]
Hi MayaStr, the bug has been fixed in the newest version of MicroStructPy, version 1.5.3. Please feel free to re-open if the issue remains.
