### ISSUE TITLE
Troubleshooting "Missing library for pygmsh on Linux" doesn't work

### ISSUE THREAD

**Issue by keisukeiwahori** [kip-hart/MicroStructPy#84]
**Describe the bug**
Troubleshooting "Missing library for pygmsh on Linux" doesn't work.

**To Reproduce**
1. To install MicroStructPy, download it from PyPI using: pip install microstructpy
2. Next, run the file from the command line: microstructpy input.xml
3. OSError: libXcursor.so.1: cannot open shared object file: No such file or directory
4. The libGLU library is misssing from the computer. To add it, run: sudo apt-get install libglu1
5. Same error appears. OSError: libXcursor.so.1: cannot open shared object file: No such file or directory

**Expected behavior**
When Step.4.

[sudo] password for iwahori:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libglu1-mesa' instead of 'libglu1'
libglu1-mesa is already the newest version (9.0.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Selected 'libglu1-mesa' instead of 'libglu1' is possible cause...

**Screenshots**
![error](https://user-images.githubusercontent.com/112057897/218421857-7f10e1f8-a302-46aa-a0a3-ea60f6453495.PNG)

**Desktop (please complete the following information):**
 - OS [Windows → WSL(Linux)]
 - Browser [MicroSoft Edge]
 - Version [ ]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by keisukeiwahori** [comment]
I could installed on windows system.

**Comment by kip-hart** [comment]
Hi @keisukeiwahori  I'm glad you were able to find a solution! I've installed MicroStructPy on a couple Linux machines without running into this issue. If you do find a fix, please feel free to submit a PR and I'll be happy to merge it.

**Comment by keisukeiwahori** [comment]
Hello kip.hart<https://pypi.org/user/kip.hart/>.

I’m keisuke iwahori form Japan.
I enjoy your MicrostructPy.

Now, I want to create 3D microstructures and export the mesh data in ABAQUS format (if can, geometry data in .x_t or .igs format).
I found a very attractive sentence in output file format.
But, I can’t know where to change “format = abaqus” indicated in bellow.
Can you tell me where the example file of 3D microstructures is?
I can’t find the example of 3D microstructures in example folder.

***@***.***

***@***.***

**Comment by kip-hart** [comment]
HI @keisukeiwahori,

Yes you can output 3D microstructures to abaqus inp files. The documentation for this function is here: https://docs.microstructpy.org/en/latest/api/meshing/trimesh.html#microstructpy.meshing.TriMesh.write.

There is a 3D example file here: https://github.com/kip-hart/MicroStructPy/blob/master/src/microstructpy/examples/two_phase_3D.xml. It doesn't generate an abaqus inp file, but if you modify it like this you'll get an inp file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<input>
    <material>
        <fraction> 1 </fraction>
        <volume>
            <dist_type> lognorm </dist_type>
            <scale> 1 </scale>
            <s> 0.95 </s>
        </volume>
        <shape> sphere </shape>
        <name> Phase 1 </name>
    </material>

    <material>
        <fraction> 3 </fraction>
        <volume>
            <dist_type> lognorm </dist_type>
            <scale> 0.5 </scale>
            <s> 1.01 </s>
        </volume>
        <name> Phase 2 </name>
    </material>

    <domain>
        <shape> cube </shape>
        <side_length> 7 </side_length>
        <corner> (0, 0, 0) </corner>
    </domain>

    <settings>
        <directory> two_phase_3D </directory>
        <verbose> True </verbose>

        <filetypes>
            <tri> abaqus </tri> <!--This setting outputs the mesh as an abaqus inp file-->
        </filetypes>

        <seeds_kwargs>
            <linewidths> 0.2 </linewidths>
        </seeds_kwargs>
        <poly_kwargs>
            <linewidths> 0.2 </linewidths>
        </poly_kwargs>
        <tri_kwargs>
            <linewidths> 0.2 </linewidths>
        </tri_kwargs>
    </settings>
</input>
```

Currently the output use the part/assembly options in Abaqus. I'm working on updating this to just be nodes and elements, but haven't pushed that to the repo yet. Let me know if I can help further.

**Comment by keisukeiwahori** [comment]
Hello kip.hart<https://pypi.org/user/kip.hart/>.

Thank you for the quick reply.
I can generate an abaqus inp file.
I checked inp file directly.
Maybe I think the information I want is contained. (Node, Element, Element set, surface・・)

Thank you!
