### ISSUE TITLE
Abaqus Output Format File - Orphan Mesh - Material Properties

### ISSUE THREAD

**Issue by MostafaMohamed2023** [kip-hart/MicroStructPy#90]
Hi Kip, 

I have to simplify my problem to be two main phases (matrix and inclusions), and I am able to import the file into Abaqus after doing this. After that, I found out that the mesh is an orphan mesh, which can't be changed, and I can't define the material properties to conduct FE simulations. 

So, could you kindly inform me what I need to do or where I can read about it?

Regards, 
Kip

**Comment by kip-hart** [comment]
Hi Mostafa,

Sorry to hear that. Could you send me a PNG of the trimesh? Email works too if you'd rather it not be public.

I'm no longer affiliated with an institution that uses Abaqus, so I am limited to the free version (up to 1000 nodes). If you can reproduce the problem with a smaller domain or coarser mesh, then I'll be able to take a look.

With the abaqus filetype, I'm strongly considering outputting a `mesh.inp` file that can be plugged into the main body of an input file that has material properties, sections, etc and just calls `*INCLUDE` to load in the mesh file. No more assembly definition, etc, just the nodes, elements, and some surface definitions like `S-X-MIN` and `S-Y-MAX` so it's easy to define boundary conditions.
I have that code somewhere already, just hadn't modified the MicroStructPy source.

Let me know your thoughts. I'd like to make sure you're up and running with using MicroStructPy meshes in Abaqus.

Best,
Kip

**Comment by kip-hart** [comment]
One more thing, if you're interested, is that I have some Python code that will introduce cohesive elements at grain boundaries. If your project needs a cohesive law at the interfaces between two phases, I have the files somewhere that'll insert zero-thickness cohesive elements at the grain boundaries.

It's on my to-do list for features to add, just hasn't been a priority recently.

**Comment by MostafaMohamed2023** [comment]
Hi Kip,

Thanks for getting back to me so quickly.
Please find it attached, and I am working on a new version with a smaller
number of nodes to send to you.
That's great about the implementation of a cohesive law; could you please
share with me your Python script?

Regards,

Mostafa M. AbdelHamid
Graduate Research Associate
Adaptive Intelligent Materials & Systems (AIMS) Center
School for Engineering of Matter, Transport, & Energy
Arizona State University
Mobile Phone: (623) 336-3553
Email: ***@***.***

**Comment by MostafaMohamed2023** [comment]
Hi Kip, 

Could you please tell me if you can open the file I've attached? I sent it twice: once yesterday through my Gmail email, and then again here.

Regards, 
Mostafa

**Comment by kip-hart** [comment]
Hi Mostafa,

I haven't received the file. Please send it to kiphart91 (at) gmail.com. 

Best,
Kip

**Comment by MostafaMohamed2023** [comment]
Hi Kip, 

Sorry for the late reply. 
I fixed my problem, but I need to know the dimensions used in MicroStructPy,  and how to define different percentages of the volume fraction. 

Regards, 
Mostafa

**Comment by kip-hart** [comment]
Hi Mostafa,

No worries, happy to hear it. The dimensions are your choosing for MicroStructPy. If you input grain sizes in millimeters, you get millimeters. It's the same approach as Abaqus.

For volume fractions, there are several examples that specify volume fractions. Internally, MicroStructPy doesn't care if the number you specify as a "fraction" is less than 1. Internally, it treats the user's input as a weight, then your volume fraction is weight/total_weight. This avoids any errors related to the input fractions not summing to 1 exactly.

For example, if you want to say you have a 5 to 2 ratio of two phases, you can say the fractions are 5 and 2, then internally MicroStructPy will use 0.714 and 0.286 as the volume fractions.

Certainly if you volume fractions you can use those too. MicroStructPy will still total them up and normalize, so if they sum to 1 then they won't change.

Best,
Kip

**Comment by MostafaMohamed2023** [comment]
Hi Kip, 

Thank you very much for this information.
I am trying to conduct a fracture analysis for 3D RVE that was created by MicroStructPy, so is there anyone before he did this analysis type? 


Regards, 
Mostafa

**Comment by kip-hart** [comment]
Hi Mostafa,

I did damage modeling with cohesive elements using 2D RVEs from MicroStructPy. That paper was just published (https://link.springer.com/article/10.1007/s00603-023-03498-7). I didn't do fracture though.

There may be some fracture analysis papers that cited MicroStructPy. The citations for the CMAME paper are (https://scholar.google.com/scholar?oi=bibs&hl=en&cites=273387373327519973&as_sdt=5) and for the SoftwareX paper are (https://scholar.google.com/scholar?oi=bibs&hl=en&cites=7565944144274847051).

Hope that helps.

Best,
Kip

**Comment by MostafaMohamed2023** [comment]
Hi Kip, 

Thanks for sharing with me this information. 
Unfortunately, I have a repeated error for each run I do now as follows: 
  File "/home/mabdelhamid/.local/lib/python3.10/site-packages/numpy/ma/core.py", line 1022, in __call__
    result = self.f(da, db, *args, **kwargs)
ValueError: operands could not be broadcast together with shapes (110,1) (0,4)

I don't have the main cause for that, so could you please help me to figure out it? 
I can also share with you my XML file to review it. 

<?xml version="1.0" encoding="UTF-8"?>
<input>
    <material>
        <fraction> 1 </fraction>
        <volume>
            <dist_type> lognorm </dist_type>
            <scale> 9 </scale>
            <s> 0.95 </s>
        </volume>
        <shape> sphere </shape>
        <name> Olivine </name>
    </material>

    <material>
        <fraction> 1 </fraction>
        <volume>
            <dist_type> lognorm </dist_type>
            <scale> 7 </scale>
            <s> 0.95 </s>
        </volume>
        <shape> sphere </shape>
        <name> Low_Ca Pyroxene </name>
    </material>


    <material>
        <fraction> 1 </fraction>
        <volume>
            <dist_type> lognorm </dist_type>
            <scale> 3 </scale>
            <s> 0.95 </s>
        </volume>
        <shape> sphere </shape>
        <name> Plagioclase </name>
    </material>

    <material>
        <fraction> 1 </fraction>
        <volume>
            <dist_type> lognorm </dist_type>
            <scale> 1 </scale>
            <s> 0.95 </s>
        </volume>
        <shape> sphere </shape>
        <name> Troilite </name>
    </material>

    <domain>
        <shape> cube </shape>
        <side_length> 10 </side_length>
        <corner> (0, 0, 0) </corner>
    </domain>

   <settings>
        <directory> Four_phases_3D</directory>
        <filetypes>
            <seeds_plot> png </seeds_plot>
            <poly_plot> png </poly_plot>
            <tri> abaqus </tri>    
            <tri_plot> png </tri_plot>
            <verify_plot> png </verify_plot>
        </filetypes>

        <plot_axes> False </plot_axes>
        <verbose> True </verbose>
        <verify> True </verify>

        <mesh_max_edge_length> 0.01 </mesh_max_edge_length>
        <mesh_min_angle> 20 </mesh_min_angle>
        <mesh_max_volume> 0.05 </mesh_max_volume>

        <seeds_kwargs>
            <linewidths> 0.2 </linewidths>
        </seeds_kwargs>
        <poly_kwargs>
            <linewidths> 0.2 </linewidths>
        </poly_kwargs>
        <tri_kwargs>
            <linewidths> 0.1 </linewidths>
        </tri_kwargs>
    </settings>
</input>


Regards, 
Mostafa

**Comment by kip-hart** [comment]
Hi Mostafa,

Using the xml input file below, I was able to generate an unstructured mesh without any errors. Give it a try and let me know if that works.

In this input file, I've turned off all the mesh controls just to get something working. Feel free to add mesh controls back to the file - in 3D the file sizes can get large quickly so I'd change them gradually. If you set it up to give you a billion elements, MicroStructPy will do it but it'll take a long time.

Best,
Kip

```xml
<?xml version="1.0" encoding="UTF-8"?>
<input>
    <material>
        <fraction> 1 </fraction>
        <volume>
            <dist_type> lognorm </dist_type>
            <scale> 7 </scale>
            <s> 0.95 </s>
        </volume>
        <shape> sphere </shape>
        <name> Low_Ca Pyroxene </name>
    </material>

    <material>
        <fraction> 1 </fraction>
        <volume>
            <dist_type> lognorm </dist_type>
            <scale> 3 </scale>
            <s> 0.95 </s>
        </volume>
        <shape> sphere </shape>
        <name> Plagioclase </name>
    </material>


    <material>
        <fraction> 1 </fraction>
        <volume>
            <dist_type> lognorm </dist_type>
            <scale> 1 </scale>
            <s> 0.95 </s>
        </volume>
        <shape> sphere </shape>
        <name> Troilite </name>
    </material>

    <domain>
        <shape> cube </shape>
        <side_length> 10 </side_length>
        <corner> (0, 0, 0) </corner>
    </domain>

    <settings>
        <filetypes>
            <tri> txt, abaqus </tri>
            <seeds_plot> png </seeds_plot>
            <poly_plot> png </poly_plot>
            <tri_plot> png </tri_plot>
            <verify_plot> png </verify_plot>
        </filetypes>

        <plot_axes> False </plot_axes>
        <verbose> True </verbose>
        <verify> True </verify>

        <mesher> gmsh </mesher>

        <seeds_kwargs>
            <linewidths> 0.2 </linewidths>
        </seeds_kwargs>
        <poly_kwargs>
            <linewidths> 0.2 </linewidths>
        </poly_kwargs>
        <tri_kwargs>
            <linewidths> 0.1 </linewidths>
        </tri_kwargs>
    </settings>
</input>
```

Here's a plot of the result:
![trimesh](https://github.com/kip-hart/MicroStructPy/assets/41959581/38daec37-0de9-4013-8c3e-38500d93d01e)

**Comment by MostafaMohamed2023** [comment]
Hi Kip, 

I am pleased to inform you that the example you sent works, and that the number of phases can be increased to four as well. I used the following volume fractions for various phases: Olivine (45%), Low-Ca Pyroxene (35%), Plagioclase (15%), and Troilite (5%).  Could you kindly verify that I have defined them correctly in my script by using the following values? Olivine (9), Low-Ca Pyroxene (7), Plagioclase (3), and Troilite (1) are the constituent minerals.

Thanks in advance for any help. 

Regards,

**Comment by kip-hart** [comment]
Hi Mostafa,

You can define it that way. You can also use Olivine (45), Low-Ca Pyroxene (35), Plagioclase (15), and Troilite (5). That'd be easier to read.

Best,
Kip

**Comment by kip-hart** [comment]
Hi Mostafa,

I'm going to close the issue ticket for now. If you have any other questions or feedback please feel free to let me know.

Best,
Kip
